
DELETE FROM Municipio;
SET IDENTITY_INSERT Municipio ON


insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('1' , '1', 'Santo Domingo de Guzmán', '1')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('2' , '2', 'Santiago de los Caballeros', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('3' , '3', 'Santo Domingo Este', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('4' , '4', 'Santo Domingo Norte', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('5' , '5', 'Santo Domingo Oeste', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('6' , '6', 'San Cristóbal', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('7' , '7', 'Concepción de la Vega', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('8' , '8', 'San Pedro de Macorís', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('9' , '9', 'La Romana', '7')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('10' , '10', 'Los Alcarrizos', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('11' , '11', 'San Francisco de Macorís', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('12' , '12', 'San Felipe de Puerto Plata', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('13' , '13', 'Salvaleón de Higüey', '10')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('14' , '14', 'Moca', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('15' , '15', 'San Juan de la Maguana', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('16' , '16', 'Bonao', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('17' , '17', 'Baní', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('18' , '18', 'Boca Chica', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('19' , '19', 'Azua de Compostela', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('20' , '20', 'Bajos de Haina', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('21' , '21', 'Villa Altagracia', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('22' , '22', 'Santa Cruz de Barahona', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('23' , '23', 'Cotuí', '17')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('24' , '24', 'Santa Cruz del Seibo', '18')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('25' , '25', 'Jarabacoa', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('26' , '26', 'Nagua', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('27' , '27', 'Samana', '20')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('28' , '28', 'Tamboril', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('29' , '29', 'Mao', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('30' , '30', 'La Victoria (D.M.)', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('31' , '31', 'Esperanza', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('32' , '32', 'Pedro Brand', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('33' , '33', 'Sosua', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('34' , '34', 'Hato Mayor del Rey', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('35' , '35', 'Constanza', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('36' , '36', 'Navarrete', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('37' , '37', 'Salcedo', '23')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('38' , '38', 'Yaguate', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('39' , '39', 'La Mata', '17')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('40' , '40', 'Las Matas de Farfán', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('41' , '41', 'Monte Plata', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('42' , '42', 'Yamasá', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('43' , '43', 'San Ignacio de Sabaneta', '25')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('44' , '44', 'San José de las Matas', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('45' , '45', 'San Antonio de Guerra', '3')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('46' , '46', 'San José de Ocoa', '26')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('47' , '47', 'Bayaguana', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('48' , '48', 'El Carril (D.M.)', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('49' , '49', 'Consuelo', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('50' , '50', 'Cambita Garabitos', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('51' , '51', 'Villa Gonzalez', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('52' , '52', 'San Gregorio de Nigua', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('53' , '53', 'Licey al Medio', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('54' , '54', 'Sánchez', '20')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('55' , '55', 'Hato del Yaque (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('56' , '56', 'San Fernando de Monte Cristi', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('57' , '57', 'Dajabón', '28')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('58' , '58', 'Comendador', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('59' , '59', 'Villa Tapia', '23')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('60' , '60', 'Neyba', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('61' , '61', 'Tenares', '23')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('62' , '62', 'Sabana Grande de Boyá', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('63' , '63', 'El Cercado', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('64' , '64', 'Imbert', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('65' , '65', 'Sabana Yegua', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('66' , '66', 'Altamira', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('67' , '67', 'Fantino', '17')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('68' , '68', 'Río Verde Arriba (D.M.)', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('69' , '69', 'Padre Las Casas', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('70' , '70', 'San Víctor (D.M.)', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('71' , '71', 'Miches', '18')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('72' , '72', 'San José de Los Llanos', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('73' , '73', 'Gaspar Hernández', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('74' , '74', 'Quisqueya', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('75' , '75', 'Villa Riva', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('76' , '76', 'Pimentel', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('77' , '77', 'Villa Montellano (D.M.)', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('78' , '78', 'Luperón', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('79' , '79', 'Maimón', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('80' , '80', 'Guaymate', '7')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('81' , '81', 'Duvergé', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('82' , '82', 'Peralvillo', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('83' , '83', 'Las Matas de Santa Cruz', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('84' , '84', 'La Canela (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('85' , '85', 'Vicente Noble', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('86' , '86', 'Castillo', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('87' , '87', 'Tireo (D.M.)', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('88' , '88', 'San Rafael del Yuma', '10')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('89' , '89', 'Cenovi (D.M.)', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('90' , '90', 'Sabana Grande de Palenque', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('91' , '91', 'Loma de Cabrera', '28')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('92' , '92', 'Río San Juan', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('93' , '93', 'Jánico', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('94' , '94', 'Villa Vásquez', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('95' , '95', 'Matanzas', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('96' , '96', 'Laguna Salada', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('97' , '97', 'Sabana de la Mar', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('98' , '98', 'Jima Abajo', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('99' , '99', 'Galván', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('100' , '100', 'Veragua (D.M.)', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('101' , '101', 'El Factor', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('102' , '102', 'Los Botados (D.M.)', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('103' , '103', 'Cabral', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('104' , '104', 'Las Terrenas', '20')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('105' , '105', 'Villa Isabela', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('106' , '106', 'Pedernales', '32')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('107' , '107', 'Castañuela', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('108' , '108', 'Arenoso', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('109' , '109', 'Los Hidalgos', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('110' , '110', 'Paya (D.M.)', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('111' , '111', 'Las Guaranas', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('112' , '112', 'Uvilla (D.M.)', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('113' , '113', 'Paraíso', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('114' , '114', 'La Otra Banda (D.M.)', '10')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('115' , '115', 'Juan López (D.M.)', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('116' , '116', 'La Peña (D.M.)', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('117' , '117', 'Enriquillo', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('118' , '118', 'Cabrera', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('119' , '119', 'Juan de Herrera', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('120' , '120', 'Tabara Arriba', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('121' , '121', 'Villa Los Almácigos', '25')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('122' , '122', 'Sabana Iglesia (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('123' , '123', 'Piedra Blanca', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('124' , '124', 'Rincon (D.M.)', '5')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('125' , '125', 'El Pozo (D.M.)', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('126' , '126', 'Vallejuelo', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('127' , '127', 'San José de Matanzas (D.M.)', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('128' , '128', 'Nizao', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('129' , '129', 'Monción', '25')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('130' , '130', 'Rancho Arriba', '26')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('131' , '131', 'Peralta', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('132' , '132', 'Sabana Larga', '26')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('133' , '133', 'Villa Jaragua', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('134' , '134', 'Jimaní', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('135' , '135', 'Sabana del Puerto (D.M.)', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('136' , '136', 'Las Yayas de Viajama', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('137' , '137', 'Pueblo Viejo', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('138' , '138', 'Hondo Valle', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('139' , '139', 'Tamayo', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('140' , '140', 'Cevicos', '17')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('141' , '141', 'Amina (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('142' , '142', 'Polo', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('143' , '143', 'Maizal (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('144' , '144', 'Matayaya (D.M.)', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('145' , '145', 'Ramon Santana', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('146' , '146', 'Pepillo Salcedo', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('147' , '147', 'El Palmar (D.M.)', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('148' , '148', 'El Rubio (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('149' , '149', 'Bohechío', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('150' , '150', 'Baitoa (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('151' , '151', 'Las Lagunas de Nisibon', '10')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('152' , '152', 'Villa Fundación (D.M.)', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('153' , '153', 'Cana Chapetón (D.M.)', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('154' , '154', 'Don Juan (D.M.)', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('155' , '155', 'Jaibón de Pueblo Nuevo (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('156' , '156', 'El Llano', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('157' , '157', 'Jamao al Norte', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('158' , '158', 'Hatillo Palma (D.M.)', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('159' , '159', 'El Valle', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('160' , '160', 'Los Ríos', '30')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('161' , '161', 'Villa Sonador (D.M.)', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('162' , '162', 'Estebania', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('163' , '163', 'Guatapanal (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('164' , '164', 'La Ciénaga', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('165' , '165', 'Guayabo Dulce (D.M.)', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('166' , '166', 'Cristo Rey de Guaraguao (D.M.)', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('167' , '167', 'Partido', '28')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('168' , '168', 'Los Cacaos', '4')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('169' , '169', 'Guayubín', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('170' , '170', 'Banica', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('171' , '171', 'Arroyo Salado (D.M.)', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('172' , '172', 'Mata Palacio (D.M.)', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('173' , '173', 'Villarpando (D.M.)', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('174' , '174', 'Cayetano Germosen', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('175' , '175', 'La Descubierta', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('176' , '176', 'Restauración', '28')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('177' , '177', 'Las Charcas', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('178' , '178', 'Pedro Corto (D.M.)', '12')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('179' , '179', 'El Pino', '28')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('180' , '180', 'Villa Elisa (D.M.)', '27')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('181' , '181', 'Santana (D.M.)', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('182' , '182', 'La Entrada (D.M.)', '19')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('183' , '183', 'Guananico', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('184' , '184', 'Juncalito (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('185' , '185', 'Cristóbal', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('186' , '186', 'Eugenio Maria de Hostos', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('187' , '187', 'José Contreras (D.M.)', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('188' , '188', 'Gonzalo (D.M.)', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('189' , '189', 'Jaibón (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('190' , '190', 'La Cueva (D.M.)', '17')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('191' , '191', 'Blanco (D.M.)', '23')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('192' , '192', 'Las Salinas', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('193' , '193', 'Jicomé (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('194' , '194', 'La Ciénaga (D.M.)', '26')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('195' , '195', 'Guayabal', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('196' , '196', 'Pizarrete (D.M.)', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('197' , '197', 'Pedro García (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('198' , '198', 'Agua Santa del Yuma (D.M.)', '8')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('199' , '199', 'Juan Santiago', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('200' , '200', 'El Puerto (D.M.)', '6')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('201' , '201', 'Palmar Arriba (D.M.)', '2')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('202' , '202', 'Pedro Sánchez (D.M.)', '18')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('203' , '203', 'Joba Arriba (D.M.)', '11')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('204' , '204', 'Pescadería (D.M.)', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('205' , '205', 'Pedro Santana', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('206' , '206', 'El Peñón', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('207' , '207', 'Jaquimeyes', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('208' , '208', 'Oviedo', '32')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('209' , '209', 'Fundación', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('210' , '210', 'Río Limpio (D.M.)', '29')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('211' , '211', 'Postrer Río', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('212' , '212', 'Canoa (D.M.)', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('213' , '213', 'Juan Adrián (D.M.)', '13')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('214' , '214', 'Juancho (D.M.)', '32')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('215' , '215', 'Yerba Buena (D.M.)', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('216' , '216', 'Palmar de Ocoa (D.M.)', '15')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('217' , '217', 'Elupina Cordero de las Cañitas(D.M.)', '22')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('218' , '218', 'Estero Hondo (D.M.)', '9')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('219' , '219', 'Guayabal (D.M.)', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('220' , '220', 'Majagual (D.M.)', '24')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('221' , '221', 'Mella', '31')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('222' , '222', 'Sabana Buey (D.M.)', '14')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('223' , '223', 'El Cachón (D.M.)', '16')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('224' , '224', 'Boca de Yuma (D.M.)', '10')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('225' , '225', 'La Caya (D.M.)', '21')
insert into Municipio (Id, Codigo, Nombre, ProvinciaId) values ('226' , '226', 'La Isabela (D.M.)', '9')
