DELETE FROM Provincia;
SET IDENTITY_INSERT Provincia ON
insert into Provincia (Id, Codigo, Nombre) values ('1', ' 001', 'Distrito Nacional')
insert into Provincia (Id, Codigo, Nombre) values ('2', ' 002', 'Santiago')
insert into Provincia (Id, Codigo, Nombre) values ('3', ' 003', 'Santo Domingo')
insert into Provincia (Id, Codigo, Nombre) values ('4', ' 004', 'San Cristóbal')
insert into Provincia (Id, Codigo, Nombre) values ('5', ' 005', 'La Vega')
insert into Provincia (Id, Codigo, Nombre) values ('6', ' 006', 'San Pedro de Macorís')
insert into Provincia (Id, Codigo, Nombre) values ('7', ' 007', 'La Romana')
insert into Provincia (Id, Codigo, Nombre) values ('8', ' 008', 'Duarte')
insert into Provincia (Id, Codigo, Nombre) values ('9', ' 009', 'Puerto Plata')
insert into Provincia (Id, Codigo, Nombre) values ('10', ' 010', 'La Altagracia')
insert into Provincia (Id, Codigo, Nombre) values ('11', ' 011', 'Espaillat')
insert into Provincia (Id, Codigo, Nombre) values ('12', ' 012', 'San Juan de la Maguana')
insert into Provincia (Id, Codigo, Nombre) values ('13', ' 013', 'Monseñor Nouel')
insert into Provincia (Id, Codigo, Nombre) values ('14', ' 014', 'Peravia')
insert into Provincia (Id, Codigo, Nombre) values ('15', ' 015', 'Azua')
insert into Provincia (Id, Codigo, Nombre) values ('16', ' 016', 'Barahona')
insert into Provincia (Id, Codigo, Nombre) values ('17', ' 017', 'Sánchez Ramírez')
insert into Provincia (Id, Codigo, Nombre) values ('18', ' 018', 'El Seibo')
insert into Provincia (Id, Codigo, Nombre) values ('19', ' 019', 'María Trinidad Sánchez')
insert into Provincia (Id, Codigo, Nombre) values ('20', ' 020', 'Samaná')
insert into Provincia (Id, Codigo, Nombre) values ('21', ' 021', 'Valverde')
insert into Provincia (Id, Codigo, Nombre) values ('22', ' 022', 'Hato Mayor')
insert into Provincia (Id, Codigo, Nombre) values ('23', ' 023', 'Hermanas Mirabal')
insert into Provincia (Id, Codigo, Nombre) values ('24', ' 024', 'Monte Plata')
insert into Provincia (Id, Codigo, Nombre) values ('25', ' 025', 'Santiago Rodríguez')
insert into Provincia (Id, Codigo, Nombre) values ('26', ' 026', 'San José de Ocoa')
insert into Provincia (Id, Codigo, Nombre) values ('27', ' 027', 'Monte Cristi')
insert into Provincia (Id, Codigo, Nombre) values ('28', ' 028', 'Dajabón')
insert into Provincia (Id, Codigo, Nombre) values ('29', ' 029', 'Elías Piña')
insert into Provincia (Id, Codigo, Nombre) values ('30', ' 030', 'Bahoruco')
insert into Provincia (Id, Codigo, Nombre) values ('31', ' 031', 'Independencia')
insert into Provincia (Id, Codigo, Nombre) values ('32', ' 032', 'Pedernales')
