//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mvc.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Formativas.
        /// </summary>
        internal static string ActividadesFormativas {
            get {
                return ResourceManager.GetString("ActividadesFormativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Formativa.
        /// </summary>
        internal static string ActividadFormativa {
            get {
                return ResourceManager.GetString("ActividadFormativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Formativa (Base).
        /// </summary>
        internal static string ActividadFormativaBase {
            get {
                return ResourceManager.GetString("ActividadFormativaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Formativas (Bases).
        /// </summary>
        internal static string ActividadFormativaBases {
            get {
                return ResourceManager.GetString("ActividadFormativaBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclos Formativos.
        /// </summary>
        internal static string CiclosFormativos {
            get {
                return ResourceManager.GetString("CiclosFormativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo.
        /// </summary>
        internal static string CrearNuevo {
            get {
                return ResourceManager.GetString("CrearNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        internal static string Distrito {
            get {
                return ResourceManager.GetString("Distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distritos.
        /// </summary>
        internal static string Distritos {
            get {
                return ResourceManager.GetString("Distritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos Étnicos.
        /// </summary>
        internal static string GruposEtnicos {
            get {
                return ResourceManager.GetString("GruposEtnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Administrativo.
        /// </summary>
        internal static string PersonalAdministrativo {
            get {
                return ResourceManager.GetString("PersonalAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        internal static string Seccion {
            get {
                return ResourceManager.GetString("Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        internal static string Tablero {
            get {
                return ResourceManager.GetString("Tablero", resourceCulture);
            }
        }
    }
}
