//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class T {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal T() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.T", typeof(T).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompañamiento.
        /// </summary>
        public static string Acompanamiento {
            get {
                return ResourceManager.GetString("Acompanamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompañante.
        /// </summary>
        public static string Acompanante {
            get {
                return ResourceManager.GetString("Acompanante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompanantes.
        /// </summary>
        public static string Acompanantes {
            get {
                return ResourceManager.GetString("Acompanantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actitudinal.
        /// </summary>
        public static string Actitudinal {
            get {
                return ResourceManager.GetString("Actitudinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Formativas.
        /// </summary>
        public static string ActividadesFormativas {
            get {
                return ResourceManager.GetString("ActividadesFormativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Formativa.
        /// </summary>
        public static string ActividadFormativa {
            get {
                return ResourceManager.GetString("ActividadFormativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad Formativa (Base).
        /// </summary>
        public static string ActividadFormativaBase {
            get {
                return ResourceManager.GetString("ActividadFormativaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades Formativas (Bases).
        /// </summary>
        public static string ActividadFormativaBases {
            get {
                return ResourceManager.GetString("ActividadFormativaBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agropecuaria.
        /// </summary>
        public static string Agropecuaria {
            get {
                return ResourceManager.GetString("Agropecuaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Años de ejercicio profesional.
        /// </summary>
        public static string AnosDeEjercicio {
            get {
                return ResourceManager.GetString("AnosDeEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMAE.
        /// </summary>
        public static string APMAE {
            get {
                return ResourceManager.GetString("APMAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asamblea de Maestros.
        /// </summary>
        public static string AsambleaDeMaestros {
            get {
                return ResourceManager.GetString("AsambleaDeMaestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aula.
        /// </summary>
        public static string Aula {
            get {
                return ResourceManager.GetString("Aula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aulas.
        /// </summary>
        public static string Aulas {
            get {
                return ResourceManager.GetString("Aulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausencia.
        /// </summary>
        public static string Ausencia {
            get {
                return ResourceManager.GetString("Ausencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausencias.
        /// </summary>
        public static string Ausencias {
            get {
                return ResourceManager.GetString("Ausencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoevaluación del Centro.
        /// </summary>
        public static string AutoevaluacionDelCentro {
            get {
                return ResourceManager.GetString("AutoevaluacionDelCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños Suficientes.
        /// </summary>
        public static string BanosSuficientes {
            get {
                return ResourceManager.GetString("BanosSuficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteca.
        /// </summary>
        public static string Biblioteca {
            get {
                return ResourceManager.GetString("Biblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando {0}.
        /// </summary>
        public static string BorrandoX {
            get {
                return ResourceManager.GetString("BorrandoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro en borrar {0}?.
        /// </summary>
        public static string BorrarConfirmacion {
            get {
                return ResourceManager.GetString("BorrarConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula.
        /// </summary>
        public static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string Centro {
            get {
                return ResourceManager.GetString("Centro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centros.
        /// </summary>
        public static string Centros {
            get {
                return ResourceManager.GetString("Centros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Sede.
        /// </summary>
        public static string CentroSede {
            get {
                return ResourceManager.GetString("CentroSede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo.
        /// </summary>
        public static string Ciclo {
            get {
                return ResourceManager.GetString("Ciclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo Formativo.
        /// </summary>
        public static string CicloFormativo {
            get {
                return ResourceManager.GetString("CicloFormativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclos Formativos.
        /// </summary>
        public static string CiclosFormativos {
            get {
                return ResourceManager.GetString("CiclosFormativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciencias Naturales.
        /// </summary>
        public static string Ciencias_Naturales {
            get {
                return ResourceManager.GetString("Ciencias_Naturales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciencias sociales.
        /// </summary>
        public static string CienciasSociales {
            get {
                return ResourceManager.GetString("CienciasSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comites de Padres Y Madres por Curso.
        /// </summary>
        public static string ComitesDePadresYMadresPorCurso {
            get {
                return ResourceManager.GetString("ComitesDePadresYMadresPorCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        public static string Componente {
            get {
                return ResourceManager.GetString("Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes.
        /// </summary>
        public static string Componentes {
            get {
                return ResourceManager.GetString("Componentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con Internet.
        /// </summary>
        public static string ConInternet {
            get {
                return ResourceManager.GetString("ConInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consejo Estudiantil.
        /// </summary>
        public static string ConsejoEstudiantil {
            get {
                return ResourceManager.GetString("ConsejoEstudiantil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consejos de Curso.
        /// </summary>
        public static string ConsejosDeCurso {
            get {
                return ResourceManager.GetString("ConsejosDeCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string Contenido {
            get {
                return ResourceManager.GetString("Contenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcta.
        /// </summary>
        public static string Correcta {
            get {
                return ResourceManager.GetString("Correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando {0}.
        /// </summary>
        public static string CreandoX {
            get {
                return ResourceManager.GetString("CreandoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo.
        /// </summary>
        public static string CrearNuevo {
            get {
                return ResourceManager.GetString("CrearNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuarto de secundaria.
        /// </summary>
        public static string CuartoSecundaria {
            get {
                return ResourceManager.GetString("CuartoSecundaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuatroBasicas.
        /// </summary>
        public static string CuatroBasicas {
            get {
                return ResourceManager.GetString("CuatroBasicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos Talleres.
        /// </summary>
        public static string CursosTalleres {
            get {
                return ResourceManager.GetString("CursosTalleres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de {0}.
        /// </summary>
        public static string DetallesDeX {
            get {
                return ResourceManager.GetString("DetallesDeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitador.
        /// </summary>
        public static string Digitador {
            get {
                return ResourceManager.GetString("Digitador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string Distrito {
            get {
                return ResourceManager.GetString("Distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string DistritoNombre {
            get {
                return ResourceManager.GetString("DistritoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distritos.
        /// </summary>
        public static string Distritos {
            get {
                return ResourceManager.GetString("Distritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docente.
        /// </summary>
        public static string Docente {
            get {
                return ResourceManager.GetString("Docente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docentes.
        /// </summary>
        public static string Docentes {
            get {
                return ResourceManager.GetString("Docentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Revisión.
        /// </summary>
        public static string DocumentoDeRevision {
            get {
                return ResourceManager.GetString("DocumentoDeRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Revisión Curricular.
        /// </summary>
        public static string DocumentoDeRevisionCurricular {
            get {
                return ResourceManager.GetString("DocumentoDeRevisionCurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string Duracion {
            get {
                return ResourceManager.GetString("Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Total.
        /// </summary>
        public static string DuracionTotal {
            get {
                return ResourceManager.GetString("DuracionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editando {0}.
        /// </summary>
        public static string EditandoX {
            get {
                return ResourceManager.GetString("EditandoX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educación Artística.
        /// </summary>
        public static string Educación_Artística {
            get {
                return ResourceManager.GetString("Educación_Artística", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educación Física.
        /// </summary>
        public static string Educación_Física {
            get {
                return ResourceManager.GetString("Educación_Física", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Buenas Condiciones.
        /// </summary>
        public static string EnBuenasCondiciones {
            get {
                return ResourceManager.GetString("EnBuenasCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Malas Condiciones.
        /// </summary>
        public static string EnMalasCondiciones {
            get {
                return ResourceManager.GetString("EnMalasCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo de Gestión.
        /// </summary>
        public static string EquipoDeGestion {
            get {
                return ResourceManager.GetString("EquipoDeGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuela de Padres y Madres.
        /// </summary>
        public static string EscuelaPadresMadres {
            get {
                return ResourceManager.GetString("EscuelaPadresMadres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante.
        /// </summary>
        public static string Estudiante {
            get {
                return ResourceManager.GetString("Estudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiantes.
        /// </summary>
        public static string Estudiantes {
            get {
                return ResourceManager.GetString("Estudiantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación.
        /// </summary>
        public static string Evaluacion {
            get {
                return ResourceManager.GetString("Evaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluaciones.
        /// </summary>
        public static string Evaluaciones {
            get {
                return ResourceManager.GetString("Evaluaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilidades de Accesibilidad.
        /// </summary>
        public static string FacilidadesDeAccesibilidad {
            get {
                return ResourceManager.GetString("FacilidadesDeAccesibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Contratación.
        /// </summary>
        public static string FechaContratacion {
            get {
                return ResourceManager.GetString("FechaContratacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        public static string FechaFin {
            get {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Finalización.
        /// </summary>
        public static string FechaFinalizacion {
            get {
                return ResourceManager.GetString("FechaFinalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación Humana y Religiosa.
        /// </summary>
        public static string Formación_Humana {
            get {
                return ResourceManager.GetString("Formación_Humana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación académica.
        /// </summary>
        public static string FormacionAcademica {
            get {
                return ResourceManager.GetString("FormacionAcademica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formador.
        /// </summary>
        public static string Formador {
            get {
                return ResourceManager.GetString("Formador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formadores.
        /// </summary>
        public static string Formadores {
            get {
                return ResourceManager.GetString("Formadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de evaluación.
        /// </summary>
        public static string FormaEvaluacion {
            get {
                return ResourceManager.GetString("FormaEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia de Actividades.
        /// </summary>
        public static string FrecuenciaActividades {
            get {
                return ResourceManager.GetString("FrecuenciaActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionarios.
        /// </summary>
        public static string Funcionarios {
            get {
                return ResourceManager.GetString("Funcionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funciones.
        /// </summary>
        public static string FuncionesEjerce {
            get {
                return ResourceManager.GetString("FuncionesEjerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados.
        /// </summary>
        public static string Grados {
            get {
                return ResourceManager.GetString("Grados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Étnico.
        /// </summary>
        public static string GrupoEtnico {
            get {
                return ResourceManager.GetString("GrupoEtnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos Étnicos.
        /// </summary>
        public static string GruposEtnicos {
            get {
                return ResourceManager.GetString("GruposEtnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        public static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informática.
        /// </summary>
        public static string Informática {
            get {
                return ResourceManager.GetString("Informática", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Período.
        /// </summary>
        public static string InformeDePeriodo {
            get {
                return ResourceManager.GetString("InformeDePeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicial.
        /// </summary>
        public static string Inicial {
            get {
                return ResourceManager.GetString("Inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripción.
        /// </summary>
        public static string Inscripcion {
            get {
                return ResourceManager.GetString("Inscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripciones.
        /// </summary>
        public static string Inscripciones {
            get {
                return ResourceManager.GetString("Inscripciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentos de Gestión Actualizados.
        /// </summary>
        public static string InstrumentosDeGestionActualizados {
            get {
                return ResourceManager.GetString("InstrumentosDeGestionActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junta de Centro.
        /// </summary>
        public static string JuntaDeCentro {
            get {
                return ResourceManager.GetString("JuntaDeCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratorio de Informática.
        /// </summary>
        public static string LabInformatica {
            get {
                return ResourceManager.GetString("LabInformatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavamanos.
        /// </summary>
        public static string Lavamanos {
            get {
                return ResourceManager.GetString("Lavamanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengua Española.
        /// </summary>
        public static string Lengua_Española {
            get {
                return ResourceManager.GetString("Lengua_Española", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguas Extranjeras.
        /// </summary>
        public static string Lenguas_Extranjeras {
            get {
                return ResourceManager.GetString("Lenguas_Extranjeras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola {0}!.
        /// </summary>
        public static string Login_Hola {
            get {
                return ResourceManager.GetString("Login_Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de Nacimiento.
        /// </summary>
        public static string LugarNacimiento {
            get {
                return ResourceManager.GetString("LugarNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestría.
        /// </summary>
        public static string Maestria {
            get {
                return ResourceManager.GetString("Maestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matemática.
        /// </summary>
        public static string Matematica {
            get {
                return ResourceManager.GetString("Matematica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matemática.
        /// </summary>
        public static string Matemática {
            get {
                return ResourceManager.GetString("Matemática", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string Matricula {
            get {
                return ResourceManager.GetString("Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria Anual.
        /// </summary>
        public static string MemoriaAnual {
            get {
                return ResourceManager.GetString("MemoriaAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Evaluación.
        /// </summary>
        public static string ModoEvaluacion {
            get {
                return ResourceManager.GetString("ModoEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo.
        /// </summary>
        public static string Monitoreo {
            get {
                return ResourceManager.GetString("Monitoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios.
        /// </summary>
        public static string Municipios {
            get {
                return ResourceManager.GetString("Municipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string Nivel {
            get {
                return ResourceManager.GetString("Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de Dominio.
        /// </summary>
        public static string NivelDominio {
            get {
                return ResourceManager.GetString("NivelDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel inicial.
        /// </summary>
        public static string NivelInicial {
            get {
                return ResourceManager.GetString("NivelInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aplica.
        /// </summary>
        public static string NoAplica {
            get {
                return ResourceManager.GetString("NoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string NombreCompleto {
            get {
                return ResourceManager.GetString("NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tiene.
        /// </summary>
        public static string NoTiene {
            get {
                return ResourceManager.GetString("NoTiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opción correcta.
        /// </summary>
        public static string OpcionCorrecta {
            get {
                return ResourceManager.GetString("OpcionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        public static string Organizacion {
            get {
                return ResourceManager.GetString("Organizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        public static string Participante {
            get {
                return ResourceManager.GetString("Participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Participantes {
            get {
                return ResourceManager.GetString("Participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string Persona {
            get {
                return ResourceManager.GetString("Persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Administrativo.
        /// </summary>
        public static string PersonalAdministrativo {
            get {
                return ResourceManager.GetString("PersonalAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        public static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Anual de Centro.
        /// </summary>
        public static string PlanAnualDeCentro {
            get {
                return ResourceManager.GetString("PlanAnualDeCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Acción.
        /// </summary>
        public static string PlanDeAccion {
            get {
                return ResourceManager.GetString("PlanDeAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Acompanamiento.
        /// </summary>
        public static string PlanDeAcompanamiento {
            get {
                return ResourceManager.GetString("PlanDeAcompanamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Mejora.
        /// </summary>
        public static string PlanDeMejora {
            get {
                return ResourceManager.GetString("PlanDeMejora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Operativo Anual.
        /// </summary>
        public static string PlanOperativoAnual {
            get {
                return ResourceManager.GetString("PlanOperativoAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Test.
        /// </summary>
        public static string PostTest {
            get {
                return ResourceManager.GetString("PostTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        public static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        public static string Preguntas {
            get {
                return ResourceManager.GetString("Preguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Test.
        /// </summary>
        public static string PreTest {
            get {
                return ResourceManager.GetString("PreTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Apellido.
        /// </summary>
        public static string PrimerApellido {
            get {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero de secundaria.
        /// </summary>
        public static string PrimeroSecundaria {
            get {
                return ResourceManager.GetString("PrimeroSecundaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimental.
        /// </summary>
        public static string Procedimental {
            get {
                return ResourceManager.GetString("Procedimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincias.
        /// </summary>
        public static string Provincias {
            get {
                return ResourceManager.GetString("Provincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Curricular de Centro.
        /// </summary>
        public static string ProyectoCurricularDeCentro {
            get {
                return ResourceManager.GetString("ProyectoCurricularDeCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Educativo de Centro.
        /// </summary>
        public static string ProyectoEducativoDeCentro {
            get {
                return ResourceManager.GetString("ProyectoEducativoDeCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Público.
        /// </summary>
        public static string Publico {
            get {
                return ResourceManager.GetString("Publico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes.
        /// </summary>
        public static string Redes {
            get {
                return ResourceManager.GetString("Redes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional.
        /// </summary>
        public static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regionales.
        /// </summary>
        public static string Regionales {
            get {
                return ResourceManager.GetString("Regionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas.
        /// </summary>
        public static string Respuestas {
            get {
                return ResourceManager.GetString("Respuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado Máximo.
        /// </summary>
        public static string ResultadoMaximo {
            get {
                return ResourceManager.GetString("ResultadoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado Mínimo.
        /// </summary>
        public static string ResultadoMinimo {
            get {
                return ResourceManager.GetString("ResultadoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salón Multi-Uso.
        /// </summary>
        public static string SalonMultiUso {
            get {
                return ResourceManager.GetString("SalonMultiUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        public static string Seccion {
            get {
                return ResourceManager.GetString("Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secciones.
        /// </summary>
        public static string Secciones {
            get {
                return ResourceManager.GetString("Secciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Educativo.
        /// </summary>
        public static string SectorEducativo {
            get {
                return ResourceManager.GetString("SectorEducativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        public static string SegundoApellido {
            get {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo de secundaria.
        /// </summary>
        public static string SegundoSecundaria {
            get {
                return ResourceManager.GetString("SegundoSecundaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su Idioma.
        /// </summary>
        public static string SeleccioneIdioma {
            get {
                return ResourceManager.GetString("SeleccioneIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Internet.
        /// </summary>
        public static string SinInternet {
            get {
                return ResourceManager.GetString("SinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio Web.
        /// </summary>
        public static string SitioWeb {
            get {
                return ResourceManager.GetString("SitioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociales.
        /// </summary>
        public static string Sociales {
            get {
                return ResourceManager.GetString("Sociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanda.
        /// </summary>
        public static string Tanda {
            get {
                return ResourceManager.GetString("Tanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico.
        /// </summary>
        public static string Tecnico {
            get {
                return ResourceManager.GetString("Tecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico profesional.
        /// </summary>
        public static string TecnicoProfesional {
            get {
                return ResourceManager.GetString("TecnicoProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnicos docente.
        /// </summary>
        public static string TecnicosDocente {
            get {
                return ResourceManager.GetString("TecnicosDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfonos.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero de secundaria.
        /// </summary>
        public static string TerceroSecundaria {
            get {
                return ResourceManager.GetString("TerceroSecundaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de objeto.
        /// </summary>
        public static string TipoDeObjeto {
            get {
                return ResourceManager.GetString("TipoDeObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evaluación.
        /// </summary>
        public static string TipoEvaluacion {
            get {
                return ResourceManager.GetString("TipoEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutores virtuales.
        /// </summary>
        public static string TutoresVirtuales {
            get {
                return ResourceManager.GetString("TutoresVirtuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor virtual.
        /// </summary>
        public static string TutorVirtual {
            get {
                return ResourceManager.GetString("TutorVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al listado.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
